name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "check out the repo"
        uses: actions/checkout@v3
      - name: "Test"
        run: |
          make test
      - name: "make release"
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          sudo make install-dependencies
          make archive REPOSITORY_NAME=${{ github.event.repository.name }}
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ github.event.repository.name }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
